name: Terraform simple infra build

on:
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Destroy Infrastructure?'
        required: false
        default: 'false'

jobs:
  terraform:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Azure Login (OIDC)
      uses: azure/login@v2
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Terraform Init
      run: terraform init

    - name: Terraform FMT
      run: terraform fmt

    - name: Terraform validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: ${{ github.event.inputs.destroy != 'true' }}
      run: terraform apply -auto-approve

    - name: Terraform Destroy
      if: ${{ github.event.inputs.destroy == 'true' }}
      run: terraform destroy -auto-approve
